dataset: CIFAR10
device: [3]

ipc: 10
syn_steps: 80
expert_epochs: 2
lr_img: 100
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset
ema_decay: 0.9995
Iteration: 10000
batch_syn: 100

# wandb
project: CIFAR10_ipc10

num_eval: 1
eval_it: 500
skip_first_eva: True

lr_y: 2.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
batch_train: 128

min_start_epoch: 0
current_max_start_epoch: 10
max_start_epoch: 20
expansion_end_epoch: 1000

lr_lr: 0.00001
zca: True

