dataset: CIFAR10
device: [0,1,2,3]

ipc: 1000
syn_steps: 100
expert_epochs: 2
lr_img: 50
lr_teacher: 0.01

buffer_path: ../buffer_storage/

data_path: ../dataset
ema_decay: 0.995
Iteration: 10000
batch_syn: 1000

# wandb
project: CIFAR10_ipc1000

num_eval: 1
eval_it: 1000
skip_first_eva: True

lr_y: 10.
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
Sequential_Generation: False
batch_train: 128
min_start_epoch: 40
max_start_epoch: 60
lr_lr: 0.00001
zca: True

